
title: Antony Leite
baseurl: "https://www.antonyleite.com/"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title/
mode: dark

author:
  name: Antony Leite
  bio: >-
    I’m Antony, also known as G4L1T0, I’m 19 years old.
  github: G4L1T0
  avatar: /assets/img/g4l1t0.png

defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

number_of_posts: 5

plugins:
  - jekyll-feed
